sudo: false
language: node_js
node_js: 9
script:
  - yarn run build
  - docker build -t ${TRAVIS_REPO_SLUG} -f docker/Dockerfile .
install:
  - yarn install
services:
  - docker
after_success:
  - travis/publish.sh
